# Site settings
name: Lary's Blog
email: clearcool@126.com
author: Lary
#url: http://xiaokedada.com
#resume_site: http://xiaokedada.com/me/
github: https://github.com/heylary/
baseurl: ""  #根目录
description: My Learn Blog。
motto: Lary's Blog
# banner: 我想带你去看绚丽的山峦，去看秀丽的溪谷，这份心情，人类是如何称呼的呢。
#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
excerpt_separator:  '<!-- more -->' #文章摘要
paginate: 8
paginate_path: "page:num"
gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
github_username: heylary
highlighter: rouge
markdown: kramdown
FB:
  comments :
    provider : disqus
    disqus :
        short_name : lary
